### ISSUE TITLE
Exception: launch Android studio and capture an exception with plugin

### ISSUE THREAD

**Issue by stevenshichn** [ishan1604/pubplug#1]
Hi 

I have copy the code and successfully install it in android studio. However, I restarted the android studio. There is an exception occur. 

PluginException: class with name "UploadAPKAction" not found [Plugin: in.ishankhanna.pubplug]

May I know how to solve it?

Thank you

**Comment by droidchef** [comment]
@stevenshichn This plugin depends on an old Google Dependency which they have deprecated and therefore the plugin is broken. 

If you are looking for something like that here is a project that can help you

https://github.com/Triple-T/gradle-play-publisher

**Comment by stevenshichn** [comment]
@ishan1604 I directly install the gradle-play-publisher file, android studio doesn't load successfully. It seems that a plugin.xml file is required. Can we directly modified the plugin.xml file and copy to the gradle-play-publisher file?

**Comment by droidchef** [comment]
@stevenshichn this plugin that I recommended is a gradle plugin and not an Android Studio plugin. 
You have to use it via your build.gradle file
